# Generated by Django 5.2.3 on 2025-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('pseudo', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
